site_name: Elye Blog
site_url: https://elye-project.medium.com/subscribe
theme:
  name: "material"
  logo: "images/logo.png"
  font:
    text: "Museo Sans"
repo_url: https://github.com/elye/blog
extra_css:
  - "stylesheets/extra.css"
nav:
  - Home: index.md
  - Software Development Experiences: software-dev-exp.md
  - Mobile Development Learning: mobile-dev-learn.md
  - Medium Blogging Learning: medium-blog-learn.md
  - Some Personal Reflection: personal-reflection.md